"use client";
import * as React from "react";
import { useState, useEffect  } from "react";
import Head from "next/head";
import HomeBar from "@/components/HomeBar";
import Stories from "@/components/Stories"
import {useSession} from "next-auth/react";
import axios from "axios";



export default function Home({}) {
    const { status, data: sessionData } = useSession();
    const [stories, setStories] = useState([]);
    useEffect( () => {
        async function getStories() {
            let storyData = await axios.get(`/api/stories`)
            if (storyData.data){
                setStories(storyData.data.stories)
                console.log(storyData.data.stories)
            }
        }
        getStories()
    },[])

  return (
    <>
      <Head>
        <title>Stories | phpiiper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id={"content"}>
        <HomeBar />
        <div id={"main-content"}>
            <h2>Stories </h2>
            <Stories stories={stories} status={{status, sessionData}} />
        </div>
      </div>
    </>
  );
}
